services:
  beetiful:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beetiful
    ports:
      - "3000:5000"  # Map host port 3000 to container port 5000
    volumes:
      # Mount your music library (adjust the host path as needed)
      - /Volumes/Media/Media/Music:/music:ro  # Read-only access to music files
      # Mount beets config directory (persistent storage)
      - ./config:/config:rw
      # Optional: Mount a directory for beets database and state
      - beetiful_data:/app/instance:rw
    environment:
      - BEETSDIR=/config
      - LIBRARY_PATH=/music
      - FLASK_PORT=5000
      - FLASK_ENV=production
    restart: unless-stopped
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  beetiful_data:
    driver: local