directory: /music
library: /config/musiclibrary.db
import:
  move: false
  copy: false
  write: true
  autotag: true
  resume: true
  incremental: true
  duplicate_action: skip
paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title
replace:
  '[\/]': _
  ^\.: _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  \.$: _
  \s+$: ''
match:
  strong_rec_thresh: 0.04
  missing_tracks: 0.9
  max_rec:
    missing_tracks: 5
    unmatched_tracks: 10
musicbrainz:
  host: musicbrainz.org
  ratelimit: 1
ui:
  color: true
  length: 79
verbose: 1
plugins:
- lyrics
lyrics:
  auto: true
  force: true
  synced: true
  sources: genius musixmatch
  fallback: ''
  lrc_file: true
  lrc_dir: /music/lyrics
  lrclib:
    source_weight: 1.0
  genius:
    source_weight: 0.8
  musixmatch:
    source_weight: 0.6
